name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '35 23 * * 5'
  push:
    branches:
      - 'main'
      - 'stable'
    paths-ignore:
      - '.github/workflows/*'

permissions:
  contents: read

jobs:
  scorecard:
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    uses: dafneb/.github/.github/workflows/scorecard.yml@824e6d2796b7a259ed4fa07dc69146b683131764 # v1.6.1
    secrets:
      SCORECARD_TOKEN: ${{ secrets.SCORECARD_TOKEN }}
