name: Snyk Code Scan

on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'stable'
      - 'release/v*'
      - 'feature/**'
      - 'issue/**'
    paths-ignore:
      - '.github/workflows/*'
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches:
      - 'main'
      - 'stable'
      - 'release/v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security:
    name: Snyk Code Scan
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: dafneb/.github/.github/workflows/snyk-code-scan-python.yml@824e6d2796b7a259ed4fa07dc69146b683131764 # v1.6.1
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
