name: Testing Python Code with Tox

on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'stable'
      - 'release/v*'
      - 'feature/**'
      - 'issue/**'
    paths-ignore:
      - '.github/workflows/*'
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches:
      - 'main'
      - 'stable'
      - 'release/v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tox:
    name: Run Tox Tests
    uses: dafneb/.github/.github/workflows/tox.yml@6904641c48f453824bb2ce384a02055cd21cbc2e # v1.6.0
